#!/usr/bin/env ruby
#Updated 26/04/2016

require 'fileutils'
require 'open-uri'

git_bundles = [
  "git@github.com:astashov/vim-ruby-debugger.git",
  "git@github.com:ervandew/supertab.git",
  "git@github.com:godlygeek/tabular.git",
  "git@github.com:depuracao/vim-rdoc.git",
  "git@github.com:msanders/snipmate.vim.git",
  "git@github.com:pangloss/vim-javascript.git",
  "git@github.com:scrooloose/nerdtree.git",
  "git@github.com:timcharper/textile.vim.git",
  "git@github.com:tpope/vim-cucumber.git",
  "git@github.com:tpope/vim-fugitive.git",
  "git@github.com:tpope/vim-git.git",
  "git@github.com:tpope/vim-haml.git",
  "git@github.com:tpope/vim-markdown.git",
  "git@github.com:tpope/vim-rails.git",
  "git@github.com:tpope/vim-repeat.git",
  "git@github.com:tpope/vim-surround.git",
  "git@github.com:tpope/vim-vividchalk.git",
  "git@github.com:vim-scripts/taskpaper.vim.git",
  "git@github.com:vim-scripts/matchit.zip.git",
  "git@github.com:tsaleh/vim-shoulda.git",
  "git@github.com:vim-scripts/tComment.git",
  "git@github.com:tsaleh/vim-tmux.git",
  "git@github.com:vim-ruby/vim-ruby.git",
  "git@github.com:vim-scripts/Gist.vim.git",
  "git@github.com:mattn/webapi-vim.git",
  "git@github.com:scrooloose/syntastic",
  "git@github.com:rodjek/vim-puppet.git",
  "git@github.com:vim-scripts/Specky.git",
  "git@github.com:Shougo/unite.vim.git",
  "git@github.com:Quramy/vison.git",
  "git@github.com:honza/vim-snippets.git",
  "git@github.com:wesQ3r/vim-windowswap.git",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))

  if url.include? "vim-snippets"
    #clearing existing snippets
    FileUtils.rm_rf(File.join("snipmate.vim", "snippets"))
    puts "copying vim-snippets to snipmate folder"
    FileUtils.cp_r("vim-snippets/snippets","snipmate.vim", :verbose=> true)
    FileUtils.rm_rf("vim-snippets")
  end
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
